services:
  - type: web
    name: khmer-spell-checker-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn backend_api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
